export const UI_CONSTANTS = {
  JOB_TITLE: "Candidate Skills Heatmap",
  SCROLL_AMOUNT: 400,
  SIDEBAR_WIDTH: 320,
  SKILL_COLUMN_WIDTH: 280,
  CANDIDATE_COLUMN_WIDTH: 40,
  MOST_RECOMMENDED_COUNT: 6,
  DEBOUNCE_DELAY_MS: 500,
} as const;
